openapi: 3.0.3
info:
  title: API for Tablo website
  contact:
    email: gitlanm@gmail.com
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
externalDocs:
  description: See our source code
  url: https://github.com/5anji/PBMenu
tags:
  - name: Restaurant
    description: Operations about restaurants
  - name: Subsidiary
    description: Operations about subsidiary
paths:
  /restaurant/get-all:
    get:
      tags:
        - Restaurant
      summary: Show all restaurants
      parameters:
        - in: query
          name: pages
          required: true
          schema:
            type: integer
          description: The number of pages
        - in: query
          name: nrOfItems
          required: true
          schema:
            type: integer
          description: The numbers of items to return

      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Restaurant"
        "400":
          description: Invalid status value
  /restaurant/save:
    post:
      tags:
        - Restaurant
      summary: Add retaurant to remote DB
      requestBody:
        description: Pagination control in site
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Restaurant"
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid status value
  /restaurant/get-by-id:
    get:
      tags:
        - Restaurant
      summary: Find restaurant by ID
      description: Returns a single restaurant
      operationId: getRestaurantById
      parameters:
        - in: query
          name: restaurantId
          description: ID of restaurant to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                properties:
                  restaurant:
                    $ref: "#/components/schemas/Restaurant"
                  subsidiaries:
                    type: array
                    items:
                      $ref: "#/components/schemas/Subsidiary"
                  food:
                    $ref: "#/components/schemas/Food"
                  drinks:
                    $ref: "#/components/schemas/Drink"
        "400":
          description: Invalid ID supplied
        "404":
          description: Restaurant not found
  /restaurant/delete:
    delete:
      tags:
        - Restaurant
      summary: Delete restaurant by ID
      description: Returns a single restaurant
      parameters:
        - in: query
          name: restaurantId
          description: ID of restaurant to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Restaurant not found
  /restaurant/detach:
    put:
      tags:
        - Restaurant
      summary: Update restaurant status
      description: Returns a single restaurant
      parameters:
        - in: query
          name: restaurantId
          description: ID of restaurant to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Restaurant not found
components:
  schemas:
    Restaurant:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: e762634c-3e41-11eb-b897-0862660ccbd4
        restaurantLogoUrl:
          type: string
          description: url of the image that will be placed as rest. preview
        photoUrl:
          type: string
          description: url of the image that will be placed as rest. preview
        name:
          type: string
          description: title under photo
        restaurantStatus:
          type: string
          enum:
            - AVAILABLE
            - DETACHED
          description: Current restaurant status
        pricing:
          type: integer
          example: 4
        phone_number:
          type: string
          description: phone numbers to contact with
          example: "+373 79123456"
        email:
          type: string
          description: mail address to contact with
          example: "qwerty@gmail.com"
        description:
          type: string
          format: any
          description: Small descrition of the restaurant
          example: Lorem ipsum vuisum mapsum libi
    Food:
      type: object
      properties:
        foodId:
          type: string
          format: uuid
          example: e762634c-3e41-11eb-b897-0862660ccbd4
        foodName:
          type: string
          example: some_food
        foodPhoto:
          type: string
        foodIngredients:
          type: string
        restaurantId:
          type: string
          format: uuid
          example: e762634c-3e41-11eb-b897-0862660ccbd4
        foodStatus:
          type: string
          enum:
            - AVAILABLE
            - DETACHED
        foodPrice:
          type: number
          format: float
          example: 66.6
        isDeliverable:
          type: boolean
        isSpicy:
          type: boolean
        isVegetarian:
          type: boolean
    Drink:
      type: object
      properties:
        drinkId:
          type: string
          format: uuid
          example: e762634c-3e41-11eb-b897-0862660ccbd4
        drinkName:
          type: string
          example: some_food
        drinkPhoto:
          type: string
        drinkIngredients:
          type: string
        drinkStatus:
          type: string
          enum:
            - AVAILABLE
            - DETACHED
        drinkPrice:
          type: number
          format: float
          example: 66.6
        isDeliverable:
          type: boolean
        isAlcoholic:
          type: boolean
        restaurantId:
          type: string
          format: uuid
          example: e762634c-3e41-11eb-b897-0862660ccbd4
    Entertaiment:
      type: object
      properties:
        Entertaiment:
          type: string
          enum:
            - Hookah
            - Playground
            - Kid Activities
    GetNumberOfPage:
      type: object
      properties:
        pages:
          type: integer
        nrOfItems:
          type: integer
    Subsidiary:
      type: object
      properties:
        subsidiaryId:
          type: string
          format: uuid
          example: e762634c-3e41-11eb-b897-0862660ccbd4
        subsidiaryName:
          type: string
          example: subsidiary name
        phoneNumber:
          type: string
          description: phone numbers to contact with
          example: "+373 79123456"
        address:
          type: string
          example: "St. cel Mare str. 1/1"
        schedule:
          type: string
          example: "7:00 - 20:00"
        entertainments:
          type: array
          description: list of available entertaiments
          items:
            $ref: "#/components/schemas/Entertaiment"
        restaurantId:
          type: string
          format: uuid
          example: e762634c-3e41-11eb-b897-0862660ccbd4
